definitions:
  app.Pager:
    properties:
      page:
        type: integer
      pagesize:
        type: integer
      total_rows:
        type: integer
    type: object
  errcode.Error:
    type: object
  model.Tag:
    properties:
      created_by:
        description: CreatedBy 创建人
        type: string
      created_on:
        description: CreatedOn 创建时间
        type: integer
      deleted_on:
        description: DeletedOn 删除时间
        type: integer
      id:
        description: Id
        type: integer
      is_del:
        description: IsDel 是否删除 0为未删除 1为已删除
        type: integer
      modified_by:
        description: ModifiedBy 修改人
        type: string
      modified_on:
        description: ModifiedOn 修改时间
        type: integer
      name:
        description: Name 标签名称
        type: string
      state:
        description: State 状态 0为禁用、1为启用
        type: integer
    type: object
  model.TagSwagger:
    properties:
      list:
        items:
          $ref: '#/definitions/model.Tag'
        type: array
      pager:
        $ref: '#/definitions/app.Pager'
    type: object
info:
  contact: {}
  description: Go语言编写博客后台
  termsOfService: blabla
  title: 博客系统
  version: "1.0"
paths:
  /api/v1/tags:
    get:
      parameters:
      - description: 标签名称
        in: query
        maxLength: 100
        name: name
        type: string
      - default: 1
        description: 状态
        enum:
        - 0
        - 1
        in: query
        name: state
        type: integer
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页数量
        in: query
        name: pagesize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TagSwagger'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 获取标签列表
  /api/v1/tags/{id}:
    get:
      parameters:
      - description: 标签ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "400":
          description: 请求错误
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: 获取标签
swagger: "2.0"
