Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPagesize: 10
  MaxPagesize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadPath: storage/upload
  UploadUrl: http://127.0.0.1:8000/static
  UploadImgMaxSize: 5
  UploadImgAllowExts:
    - .jpg
    - .jpeg
    - .png
JWT:
  Secret: secret_ppp
  Issuer: blog_service
  Expire: 7200
